apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: unassigned-maintenances
spec:
  schedule: 36 19 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  ConcurrencyPolicy: Forbid
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:
            parent: "unassigned-maintenance"
        spec:
          containers:
          - name: unassigned-maintenances
            image: docker-registry.default.svc:5000/unassigned-maintenance-broadcast-system/unassigned-maintenances
            env:
              - name: DEDICATED_USER
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: DEDICATED_USER
              - name: DEDICATED_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: DEDICATED_TOKEN
              - name: EMAIL_SENDER
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: EMAIL_SENDER
              - name: EMAIL_RECIPIENT
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: EMAIL_RECIPIENT
              - name: SOURCE_REPO
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: SOURCE_REPO
              - name: NAMESPACE
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: NAMESPACE
              - name: CLUSTER
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: CLUSTER
          restartPolicy: OnFailure 
