apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pi
spec:
  schedule: "00 00 * * *"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  ConcurrencyPolicy: Forbid
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:
            parent: "unassigned-maintenance"
        spec:
          containers:
          - name: unassigned-maintenance
            image: unassigned-maintenance
            env:
              - name: DEDICATED_USER
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: DEDICATED_USER
              - name: DEDICATED_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: DEDICATED_TOKEN
              - name: EMAIL_SENDER
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: EMAIL_SENDER
              - name: EMAIL_RECIPIENT
                valueFrom:
                  secretKeyRef:
                    name: unassigned-maintenance-config
                    key: EMAIL_RECIPIENT
          restartPolicy: OnFailure 
